# Generated by Django 3.2.7 on 2021-12-09 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0003_category_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='website',
        ),
    ]
